### ISSUE TITLE
Multiple remote sources

### ISSUE THREAD

**Issue by vlad-saling** [davidtheclark/list-selectors#5]
I might be missing something obvious but is there an out-of-the-box option to feed in multiple remote sources like in CLI? I've tried to do something like:

``` js
function getSelectors(res,selectors,url,last) {
  listSelectors(
    ['www.style.com/style1.css', 'www.style.com/style2.css'], // source
    { include: selectors }, // options
    function(myList) { // callback
      //list selectors from URLs
    }
  );
}
```

But I get the result for only the very first remote.

**Comment by davidtheclark** [comment]
@vlad-saling Sorry for the delay: was on vacation. No, that's not supported. I don't think it's entirely necessary to build in support for multiple URLs. A little bit of code within your `getSelectors` function and you should be able to get what you want, without needing to modify the API of this module :)

**Comment by vlad-saling** [comment]
@davidtheclark No problem at all :) hope you had nice time and got some rest. Even though I think, that built-in support would be nice, you are right, that this can be achieved rather easily with a little extra code and thus not necessary. In the meantime I solved it myself with arrays and promises.
