### ISSUE TITLE
Use with text string

### ISSUE THREAD

**Issue by tomgallagher** [davidtheclark/list-selectors#6]
Hello

What's the best way to use this in straight node.js implementation if I want to list the selectors included in the text of the css file that I have fetched from a remote URL?

Do I need to write to the file system and read from there? Is there an easier way where I can work from an object in memory?

Thanks.

**Comment by davidtheclark** [comment]
@tomgallagher: How about using it as a PostCSS plugin (https://github.com/davidtheclark/list-selectors#as-postcss-plugin), and using PostCSS to read your in-memory CSS?

**Comment by tomgallagher** [comment]
Perfect. If you think that's the best way. I was looking at PostCSS for something else. Is it fast?

**Comment by davidtheclark** [comment]
> Is it fast?

As fast as I've ever needed: never had any complaint about its speed.
