### ISSUE TITLE
Please could you update lodash dependency to non vulnerable version

### ISSUE THREAD

**Issue by ainthek** [davidtheclark/list-selectors#8]
$ snyk test list-selectors
(node:9328) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

Testing list-selectors...

✗ Medium severity vulnerability found in lodash
  Description: Regular Expression Denial of Service (ReDoS)
  Info: https://snyk.io/vuln/SNYK-JS-LODASH-73639
  Introduced through: lodash@3.10.1
  From: lodash@3.10.1

✗ Medium severity vulnerability found in lodash
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/npm:lodash:20180130
  Introduced through: lodash@3.10.1
  From: lodash@3.10.1

✗ High severity vulnerability found in lodash
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-LODASH-450202
  Introduced through: lodash@3.10.1
  From: lodash@3.10.1

✗ High severity vulnerability found in lodash
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-LODASH-73638
  Introduced through: lodash@3.10.1
  From: lodash@3.10.1

Organization:      ainthek
Package manager:   npm
Open source:       yes
Project path:      list-selectors

Tested list-selectors for known vulnerabilities, found 4 vulnerabilities, 4 vulnerable paths.

**Comment by TriangleJuice** [comment]
+1

**Comment by ainthek** [comment]
clear abandonware ;-)

**Comment by davidtheclark** [comment]
Yep, I'm not actively maintaining this. Feel free to fork.

**Comment by deammer** [comment]
@ainthek and @TriangleJuice we've just published version 2.0.1, check it out!
